<?php

namespace UniaAlfa\Phpxdebug\Domain;

use Exception;

class Cliente
{
    protected string $nome;
    protected string $email;
    protected string $idade;
    protected string $cpf;
    protected Endereco $endereco;

    public function populaCliente(array $cliente, Endereco $endereco) 
    {
        $this->nome = $cliente['nome'];
        $this->email = $cliente['email'];
        $this->idade = $cliente['idade'];
        $this->cpf = $cliente['cpf'];
        $this->endereco = $endereco;
    }

    public function imprimeDadosCliente() 
    {
        return [
            "nome" => $this->nome,
            "email" => $this->email,
            "cpf" => $this->cpf,
            "idade" => $this->idade,
            "endereco" => $this->endereco->imprimeEndereco(),
        ];
    }

    private function setNome($nome)
    {

        if (empty($nome)) {
            throw new Exception("O campo nome n達o pode ser vazio");
        }
        $this->nome = $nome;

        return $this;
    }

    private function setEmail($email)
    {   
        if (empty($email)) {
            throw new Exception("O campo email n達o pode ser vazio");
        }
        $this->nome = $email;

        return $this;
    }

    private function setIdade($idade)
    {
        if (empty($idade)) {
            throw new Exception("O campo idade n達o pode ser vazio");
        }
        $this->nome = $idade;

        return $this;
    }

    private function setCpf($cpf)
    {
        if (empty($cpf)) {
            throw new Exception("O campo cpf n達o pode ser vazio");
        }
        $this->nome = $cpf;

        return $this;
    }

   
}